"""initial schema with work arrangement and date filters

Revision ID: 10863820fde7
Revises: 
Create Date: 2026-05-15 03:41:02.840579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10863820fde7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discovered_jobs', sa.Column('work_arrangement', sa.String(length=20), nullable=True))
    op.add_column('discovered_jobs', sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('job_search_profiles', sa.Column('work_arrangements', sa.String(length=100), nullable=True))
    op.add_column('job_search_profiles', sa.Column('posted_within_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_search_profiles', 'posted_within_days')
    op.drop_column('job_search_profiles', 'work_arrangements')
    op.drop_column('discovered_jobs', 'posted_at')
    op.drop_column('discovered_jobs', 'work_arrangement')
    # ### end Alembic commands ###
