"""add github_url and website_url to users

Revision ID: de46f82dc80b
Revises: 10863820fde7
Create Date: 2026-05-26 04:59:17.131781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de46f82dc80b'
down_revision: Union[str, None] = '10863820fde7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('website_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'website_url')
    op.drop_column('users', 'github_url')
    # ### end Alembic commands ###
