"""gmail automation: labels, send, followups

Revision ID: c5cb960c646c
Revises: 3b79aa6c314c
Create Date: 2026-05-28 04:30:17.018584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5cb960c646c'
down_revision: Union[str, None] = '3b79aa6c314c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sent_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('to_addr', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=998), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('gmail_message_id', sa.String(length=255), nullable=True),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['job_applications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sent_emails_app_kind', 'sent_emails', ['application_id', 'kind'], unique=False)
    op.create_index(op.f('ix_sent_emails_id'), 'sent_emails', ['id'], unique=False)
    op.create_index(op.f('ix_sent_emails_user_id'), 'sent_emails', ['user_id'], unique=False)
    op.add_column('job_applications', sa.Column('last_human_email_from', sa.String(length=320), nullable=True))
    op.add_column('job_applications', sa.Column('last_human_email_thread_id', sa.String(length=255), nullable=True))
    op.add_column('job_applications', sa.Column('last_human_email_msgid', sa.String(length=998), nullable=True))
    op.add_column('job_applications', sa.Column('followup_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('gmail_scopes', sa.Text(), nullable=True))
    # server_default backfills existing rows; NOT NULL would otherwise fail on them.
    op.add_column('users', sa.Column('auto_label_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('auto_followup_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('users', sa.Column('followup_after_days', sa.Integer(), nullable=False, server_default='7'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'followup_after_days')
    op.drop_column('users', 'auto_followup_enabled')
    op.drop_column('users', 'auto_label_enabled')
    op.drop_column('users', 'gmail_scopes')
    op.drop_column('job_applications', 'followup_sent_at')
    op.drop_column('job_applications', 'last_human_email_msgid')
    op.drop_column('job_applications', 'last_human_email_thread_id')
    op.drop_column('job_applications', 'last_human_email_from')
    op.drop_index(op.f('ix_sent_emails_user_id'), table_name='sent_emails')
    op.drop_index(op.f('ix_sent_emails_id'), table_name='sent_emails')
    op.drop_index('ix_sent_emails_app_kind', table_name='sent_emails')
    op.drop_table('sent_emails')
    # ### end Alembic commands ###
