"""gmail connection + application stage

Revision ID: 3b79aa6c314c
Revises: b2c3d4e5f6a7
Create Date: 2026-05-28 02:44:15.423211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b79aa6c314c'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('stage', sa.String(length=20), nullable=True))
    op.add_column('job_applications', sa.Column('stage_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('gmail_email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('gmail_access_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('gmail_refresh_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('gmail_token_expiry', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('gmail_connected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('gmail_last_synced_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gmail_last_synced_at')
    op.drop_column('users', 'gmail_connected_at')
    op.drop_column('users', 'gmail_token_expiry')
    op.drop_column('users', 'gmail_refresh_token')
    op.drop_column('users', 'gmail_access_token')
    op.drop_column('users', 'gmail_email')
    op.drop_column('job_applications', 'stage_updated_at')
    op.drop_column('job_applications', 'stage')
    # ### end Alembic commands ###
