"""add job_pool table

Revision ID: 9b6db8726e3f
Revises: 0696a7f5c1e6
Create Date: 2026-05-29 04:25:00.583991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b6db8726e3f'
down_revision: Union[str, None] = '0696a7f5c1e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('work_arrangement', sa.String(length=20), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('search_query', sa.String(length=255), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_pool_id'), 'job_pool', ['id'], unique=False)
    op.create_index(op.f('ix_job_pool_job_url'), 'job_pool', ['job_url'], unique=True)
    op.create_index(op.f('ix_job_pool_last_seen_at'), 'job_pool', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_job_pool_search_query'), 'job_pool', ['search_query'], unique=False)
    op.create_index(op.f('ix_job_pool_source'), 'job_pool', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_pool_source'), table_name='job_pool')
    op.drop_index(op.f('ix_job_pool_search_query'), table_name='job_pool')
    op.drop_index(op.f('ix_job_pool_last_seen_at'), table_name='job_pool')
    op.drop_index(op.f('ix_job_pool_job_url'), table_name='job_pool')
    op.drop_index(op.f('ix_job_pool_id'), table_name='job_pool')
    op.drop_table('job_pool')
    # ### end Alembic commands ###
